trigger:
  - lithium

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    apt-get install -y docker.io && systemctl start docker
    ./docker-build.sh
  displayName: 'Building the package...'
- script: |
    latest_tag=$(git describe --tags --abbrev=0)
    echo "##vso[task.setvariable variable=latest_tag]${latest_tag}"
  displayName: 'Getting the latest git tag...'
- task: CopyFiles@2
  inputs:
    Contents: 'build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'bunsen-os-release'